server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      url: jdbc:mysql://10.0.251.142:9002/school?allowMulitiQueries=true&useUnicode=true&characterEncoding=UTF-8
      password: school2020
  redis:
    host: 10.0.251.142
    port: 9001
    password: school2020
    database: 1
  elasticsearch:
    hosts: 10.0.251.142:9003
